# plugin-sync-version: 2
# SessionStart hook: propagate newly-installed plugins across all CC profiles.
#
# There is no native "plugin installed" event, so we reconcile at session start:
# any plugin enabled (True) in ANY profile is added to every profile that is
# MISSING the key entirely. A plugin explicitly present as False is an
# intentional per-profile opt-out and is NEVER touched — so this never fights a
# deliberate disable, it only fills gaps. Marketplaces propagate the same way
# (setdefault). Writes are atomic + only-if-changed, so a no-op session start
# costs a handful of small JSON reads and zero writes. Fail-open.
#
# v2 (managed by Castellyn, Plugins tab): the PROFILES list below is generated by
# Castellyn from its profiles config whenever the hook is installed or refreshed.
# A directory scan is deliberately NOT used: sibling dirs like ~/.claude-mem
# (claude-mem's data) also hold a settings.json and must never be touched.
# Manual edits to this file are overwritten on hook updates — edit via Castellyn.
import json
import os
import sys

HOME = os.path.expanduser("~")

PROFILES = [".claude"]  # castellyn:profiles


def load(fp):
    try:
        return json.load(open(fp, encoding="utf-8"))
    except Exception:
        return None


def reconcile(profiles=None, home=HOME):
    """Return list of (profile, added_plugins, added_markets) actually written."""
    if profiles is None:
        profiles = PROFILES
    settings = {}
    for p in profiles:
        fp = os.path.join(home, p, "settings.json")
        if os.path.isfile(fp) and not os.path.islink(fp):
            d = load(fp)
            if isinstance(d, dict):
                settings[p] = (fp, d)

    # canonical: plugins True anywhere, and every marketplace definition seen
    enabled = set()
    markets = {}
    for _, d in settings.values():
        for name, val in (d.get("enabledPlugins") or {}).items():
            if val is True:
                enabled.add(name)
        for mk, defn in (d.get("extraKnownMarketplaces") or {}).items():
            if defn and mk not in markets:
                markets[mk] = defn

    changes = []
    for p, (fp, d) in settings.items():
        ep = d.get("enabledPlugins")
        if ep is None:
            ep = d["enabledPlugins"] = {}
        mk = d.get("extraKnownMarketplaces")
        if mk is None:
            mk = d["extraKnownMarketplaces"] = {}
        added_p = [n for n in enabled if n not in ep]   # only fill MISSING keys
        added_m = [m for m in markets if m not in mk]
        if not added_p and not added_m:
            continue
        for n in added_p:
            ep[n] = True
        for m in added_m:
            mk[m] = markets[m]
        tmp = fp + ".tmp"
        with open(tmp, "w", encoding="utf-8") as f:
            json.dump(d, f, ensure_ascii=False, indent=2)
        os.replace(tmp, fp)
        changes.append((p, added_p, added_m))
    return changes


def main():
    # As a SessionStart hook stay silent on no-op (any output lands in the CC session
    # context every start); --verbose (Castellyn's "sync now") always reports.
    verbose = "--verbose" in sys.argv
    changes = reconcile()
    if not changes:
        if verbose:
            print("[plugin-sync] no-op: all profiles already in sync")
        return
    total = sorted({n for _, ap, _ in changes for n in ap})
    profs = ", ".join(p for p, _, _ in changes)
    if total:
        names = ", ".join(n.split("@")[0] for n in total)
        print(f"[plugin-sync] распространил плагины в профили ({profs}): {names}. "
              "Применится при следующем старте этих профилей.")
    else:
        print(f"[plugin-sync] распространил маркетплейсы в профили: {profs}")


if __name__ == "__main__":
    try:
        main()
    except Exception:
        pass  # fail-open
    sys.exit(0)
